# Generated by Django 5.1 on 2024-08-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_alter_telegramuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
