# Generated by Django 5.1 on 2024-08-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('telegram_users', '0002_alter_telegramuser_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('date',), name='date'),
        ),
    ]
